### ISSUE TITLE
可以将变暗替换为其他素材吗？

### ISSUE THREAD

**Issue by FiveHair** [Krash220/OBS-Anti-Flashbang#1]
可以将变暗替换为其他素材吗？
比如检测到闪光叠加一张图片
或者检测到闪光让指定来源显示

做成原神启动那种效果哈哈

**Comment by InformationKiller** [comment]
理论上是可行的，用obs的lua接口加载一张图片或者把变暗改成调低alpha通道这样就能把底下的图片显示出来了……不过我不打算在我的版本这样搞，你可以fork一份自己改改看

**Comment by FiveHair** [comment]
用python实现了，检测到指定窗口全白就显示某个素材
